package io.lundie.gradle.jokegenius.apiutils;

import android.os.AsyncTask;
import android.util.Log;

import java.io.IOException;

import io.lundie.gradle.jokegenius.backend.myApi.MyApi;

import static io.lundie.gradle.jokegenius.apiutils.FetchStatus.API_RETRIEVE_ERROR;
import static io.lundie.gradle.jokegenius.apiutils.FetchStatus.FETCH_SUCCESS;
import static io.lundie.gradle.jokegenius.apiutils.FetchStatus.IO_EXCEPTION_ERROR;
import static io.lundie.gradle.jokegenius.apiutils.FetchStatus.RETURNED_EMPTY;

/**
 * Subclass of {@link AsyncTask}, connecting to our Google Cloud Endpoints API
 * service and retrieving requested data.
 */
public class EndpointsAsyncTask extends AsyncTask<Void, Void, String> {

    private static final String LOG_TAG = EndpointsAsyncTask.class.getName();

    private MyApi myApiService;
    private AsyncCallback asyncCallback;
    private AsyncFetchStatus asyncFetchStatus;

    /**
     * Constructor for EndpointsAsyncTask. Task is generated by a factory class, in order
     * to facilitate injection of the below params.
     * Note: This should not be a singleton object, and should be recreated every time an Async
     * request is made.
     * @param apiService {@link io.lundie.gradle.jokegenius.injection.modules.ApiModule}
     * @param asyncCallback {@link JokeLiveData}
     */
    public EndpointsAsyncTask(MyApi apiService, AsyncCallback asyncCallback,
                              AsyncFetchStatus asyncFetchStatus) {
        this.myApiService = apiService;
        this.asyncCallback = asyncCallback;
        this.asyncFetchStatus = asyncFetchStatus;
    }

    @Override
    protected String doInBackground(Void... voids) {
        if(myApiService !=null) {
            try {
                return myApiService.getJoke().execute().getData();
            } catch (IOException e) {
                asyncFetchStatus.post(IO_EXCEPTION_ERROR);
                Log.e(LOG_TAG, e.getMessage());
                // Note that in order to fulfill Udacity Project Rubric (re: testing), we are
                // returning an empty string. Errors are handled through the View Model.
                return "";
            }
        }
        asyncFetchStatus.post(API_RETRIEVE_ERROR);
        Log.e(LOG_TAG, "Error retrieving API service.");
        return "";
    }

    @Override
    protected void onPostExecute(String result) {
        String jokeData = result;
        Log.e(LOG_TAG, "JOKE DATA: " + result);
        if(asyncCallback != null) {
            if(jokeData.isEmpty()) {
                asyncFetchStatus.set(RETURNED_EMPTY);
                jokeData = "";
            } else {
                Log.e(LOG_TAG, "SETTING FETCH --> SUCCESS");
                asyncFetchStatus.set(FETCH_SUCCESS);
            }
            asyncCallback.processJokeData(jokeData);
        }else{
            Log.e(LOG_TAG, "AsyncCallback reference was not post correctly.");
        }
    }
}